language: python
python: 2.7


env:
    - OMV_ENGINE=jNeuroML

install:
    
    # Install OMV
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation


    # Install libNeuroML (development version) & dependencies

    - git clone https://github.com/NeuralEnsemble/libNeuroML.git
    - cd libNeuroML
    - git checkout development
    - python setup.py install
    - cd
    

    # Install pyNeuroML
    - pip install git+https://github.com/NeuroML/pyNeuroML.git


    #   Install OSB API
    - git clone https://github.com/OpenSourceBrain/OSB_API.git
    - cd OSB_API/python
    - python setup.py install

    

script:
    - cd Channelpedia
    - python ChannelpediaToNeuroML2.py HCN1
    - $JNML_HOME/jnml LEMS_Test_HCN1.xml -nogui
    - python analyse.py
    - python NML2ChannelAnalyse.py Nav1.3.channel.nml Channelpedia_Nav1_3_43
    - $JNML_HOME/jnml LEMS_Test_Channelpedia_Nav1_3_43.xml -nogui

    - omv all -V
    
    
