language: python
python: 2.7


install:
    - pwd
    - cd
    - svn checkout https://svn.code.sf.net/p/neuroml/code/jNeuroMLJar
    - export JNML_HOME=$HOME/jNeuroMLJar
    - cd $TRAVIS_BUILD_DIR
    

script:
    - env
    - pwd
    - ls
    - cd Channelpedia
    - echo $JNML_HOME
    - ls -alt $JNML_HOME
    - $JNML_HOME/jnml -v
